version: '3'
services:
  rabbitmq:
    image: "rabbitmq:3-management"
    ports:
      - "5671:5671"
      - "5672:5672"
      - "25672:25672"
      - "15671:15671"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_PASS: guest
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_VHOST: vhost
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:15672"]
      interval: 30s
      timeout: 10s
      retries: 5

  database:
    build: ./db
    ports:
      - 27017:27017

  server:
    build: ./server
    ports:
      - "8080:8080"
    volumes:
      - ./server/:/usr/src/app
      - /usr/src/app/node_modules
    links:
      - rabbitmq
      - database
    environment:
      - AMPQ_ADDRESS=amqp://guest:guest@rabbitmq:5672/vhost
    restart: always
    depends_on:
      - "database"
      - "rabbitmq"

  client:
    image: ambientum/node:9
    volumes:
      - ./web:/var/www/app/
    command: bash -c "yarn && npm run dev"
    ports:
      - 3000:3000
    depends_on:
      - "server"
